sequenceDiagram
    participant Заказ1
    participant Курьер1
    participant Курьер2
    participant Заказ2

    note over Заказ1: Формирование списка курьеров
    Заказ1 ->> Курьер1: Запрос параметров
    Заказ1 ->> Курьер2: Запрос параметров

    note over Заказ2: Формирование списка курьеров
    Заказ2 ->> Курьер1: Запрос параметров
    Заказ2 ->> Курьер2: Запрос параметров

    Курьер1 ->> Заказ1: Параметры: время, цена

    note over Заказ1: Все курьеры ответили?\nНет, ожидаем всех ответов
    Курьер1 ->> Заказ2: Параметры: время, цена

    note over Заказ2: Все курьеры ответили?\nНет, ожидаем все ответов
    Курьер2 ->> Заказ1: Параметры: время, цена

    note over Заказ1: Все курьеры ответили?\nДа, оцениваем варианты
    note over Заказ1: Выбор лучшего варианта

    Заказ1 ->> Курьер1: Прошу запланировать по варианту
    Курьер1 ->> Заказ1: Принято, вариант запланирован

    Курьер2 ->> Заказ2: Параметры: время, цена

    note over Заказ2: Все курьеры ответили?\nДа, оцениваем варианты
    note over Заказ2: Выбор лучшего варианта

    Заказ2 ->> Курьер1: Прошу запланировать по варианту
    Курьер1 ->> Заказ2: Отказ, вариант уже невыполним

    note over Заказ2: Выбор лучшего варианта
    Заказ2 ->> Курьер2: Прошу запланировать по варианту
    Курьер2 ->> Заказ2: Принято, вариант запланирован